ALTER TABLE "PlayerInventory" ADD COLUMN "healingPills" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerInventory" ADD COLUMN "focusPills" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerInventory" ADD COLUMN "guardPills" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerInventory" ADD COLUMN "clarityPills" INTEGER NOT NULL DEFAULT 0;
