import type { AbilitySeedDefinition } from './types';

export const abilitySeed = [
  {
    code: 'ember_pulse',
    name: 'Импульс углей',
    description: 'Базовый активный рунный навык архетипа огня.',
    kind: 'ACTIVE',
    target: 'ENEMY',
    runeArchetypeCode: 'ember',
    manaCost: 3,
    cooldownTurns: 2,
    tags: ['damage', 'starter', 'fire'],
  },
  {
    code: 'ember_heart',
    name: 'Сердце углей',
    description: 'Пассивно усиливает атакующее давление владельца руны.',
    kind: 'PASSIVE',
    target: 'SELF',
    runeArchetypeCode: 'ember',
    manaCost: 0,
    cooldownTurns: 0,
    tags: ['passive', 'fire', 'attack'],
  },
  {
    code: 'stone_guard',
    name: 'Каменный дозор',
    description: 'Пассивно усиливает выживаемость и защиту.',
    kind: 'PASSIVE',
    target: 'SELF',
    runeArchetypeCode: 'stone',
    manaCost: 0,
    cooldownTurns: 0,
    tags: ['passive', 'defence', 'stone'],
  },
  {
    code: 'gale_step',
    name: 'Шаг шквала',
    description: 'Активный манёвр, который должен лечь в будущую систему темпа и инициативы.',
    kind: 'ACTIVE',
    target: 'SELF',
    runeArchetypeCode: 'gale',
    manaCost: 2,
    cooldownTurns: 2,
    tags: ['active', 'tempo', 'gale'],
  },
  {
    code: 'echo_mind',
    name: 'Эхо разума',
    description: 'Пассивно усиливает интеллект и магическую глубину руны.',
    kind: 'PASSIVE',
    target: 'SELF',
    runeArchetypeCode: 'echo',
    manaCost: 0,
    cooldownTurns: 0,
    tags: ['passive', 'magic', 'echo'],
  },
] satisfies readonly AbilitySeedDefinition[];
