import type { MobTemplateSeedDefinition } from './types';

export const mobSeed = [
  {
    biomeCode: 'initium',
    code: 'training-wisp',
    name: 'Учебный огонёк',
    kind: 'spirit',
    isElite: false,
    isBoss: false,
    baseHealth: 8,
    baseAttack: 1,
    baseDefence: 0,
    baseMagicDefence: 0,
    baseDexterity: 2,
    baseIntelligence: 1,
    healthScale: 1.05,
    attackScale: 1.03,
    defenceScale: 1.02,
    magicDefenceScale: 1.02,
    dexterityScale: 1.03,
    intelligenceScale: 1.02,
    baseExperience: 6,
    baseGold: 2,
    runeDropChance: 10,
    lootTable: JSON.stringify({ herb: 1 }),
    attackText: 'касается искрой',
  },
  {
    biomeCode: 'dark-forest',
    code: 'blue-slime',
    name: 'Синий слизень',
    kind: 'slime',
    isElite: false,
    isBoss: false,
    baseHealth: 12,
    baseAttack: 3,
    baseDefence: 1,
    baseMagicDefence: 0,
    baseDexterity: 2,
    baseIntelligence: 1,
    healthScale: 1.14,
    attackScale: 1.08,
    defenceScale: 1.08,
    magicDefenceScale: 1.04,
    dexterityScale: 1.06,
    intelligenceScale: 1.02,
    baseExperience: 10,
    baseGold: 4,
    runeDropChance: 18,
    lootTable: JSON.stringify({ herb: 1, leather: 1 }),
    attackText: 'шлёпает студенистым телом',
  },
  {
    biomeCode: 'dark-forest',
    code: 'forest-wolf',
    name: 'Лесной волк',
    kind: 'wolf',
    isElite: false,
    isBoss: false,
    baseHealth: 15,
    baseAttack: 4,
    baseDefence: 1,
    baseMagicDefence: 0,
    baseDexterity: 4,
    baseIntelligence: 2,
    healthScale: 1.16,
    attackScale: 1.10,
    defenceScale: 1.07,
    magicDefenceScale: 1.03,
    dexterityScale: 1.10,
    intelligenceScale: 1.03,
    baseExperience: 14,
    baseGold: 5,
    runeDropChance: 22,
    lootTable: JSON.stringify({ leather: 2, bone: 1 }),
    attackText: 'впивается клыками',
  },
  {
    biomeCode: 'dark-forest',
    code: 'ash-seer',
    name: 'Пепельная ведунья',
    kind: 'mage',
    isElite: true,
    isBoss: false,
    baseHealth: 24,
    baseAttack: 7,
    baseDefence: 2,
    baseMagicDefence: 4,
    baseDexterity: 5,
    baseIntelligence: 8,
    healthScale: 1.16,
    attackScale: 1.09,
    defenceScale: 1.08,
    magicDefenceScale: 1.09,
    dexterityScale: 1.08,
    intelligenceScale: 1.10,
    baseExperience: 24,
    baseGold: 9,
    runeDropChance: 28,
    lootTable: JSON.stringify({ herb: 2, essence: 1 }),
    attackText: 'выпускает пепельный прорыв',
  },
  {
    biomeCode: 'dark-forest',
    code: 'stonehorn-ram',
    name: 'Камнерогий таран',
    kind: 'boar',
    isElite: true,
    isBoss: false,
    baseHealth: 30,
    baseAttack: 8,
    baseDefence: 4,
    baseMagicDefence: 1,
    baseDexterity: 4,
    baseIntelligence: 2,
    healthScale: 1.17,
    attackScale: 1.09,
    defenceScale: 1.09,
    magicDefenceScale: 1.04,
    dexterityScale: 1.07,
    intelligenceScale: 1.02,
    baseExperience: 26,
    baseGold: 10,
    runeDropChance: 30,
    lootTable: JSON.stringify({ leather: 2, bone: 1, metal: 1 }),
    attackText: 'врезается всем весом',
  },
  {
    biomeCode: 'dark-forest',
    code: 'blind-augur',
    name: 'Слепой авгур',
    kind: 'spirit',
    isElite: true,
    isBoss: false,
    baseHealth: 22,
    baseAttack: 6,
    baseDefence: 2,
    baseMagicDefence: 5,
    baseDexterity: 6,
    baseIntelligence: 9,
    healthScale: 1.15,
    attackScale: 1.08,
    defenceScale: 1.06,
    magicDefenceScale: 1.10,
    dexterityScale: 1.08,
    intelligenceScale: 1.10,
    baseExperience: 24,
    baseGold: 9,
    runeDropChance: 28,
    lootTable: JSON.stringify({ herb: 1, essence: 2 }),
    attackText: 'срывает покров будущего ударом духа',
  },
  {
    biomeCode: 'dark-forest',
    code: 'storm-lynx',
    name: 'Шквальная рысь',
    kind: 'wolf',
    isElite: true,
    isBoss: false,
    baseHealth: 23,
    baseAttack: 7,
    baseDefence: 2,
    baseMagicDefence: 2,
    baseDexterity: 9,
    baseIntelligence: 5,
    healthScale: 1.15,
    attackScale: 1.09,
    defenceScale: 1.06,
    magicDefenceScale: 1.05,
    dexterityScale: 1.11,
    intelligenceScale: 1.05,
    baseExperience: 24,
    baseGold: 9,
    runeDropChance: 28,
    lootTable: JSON.stringify({ leather: 1, herb: 1, essence: 1 }),
    attackText: 'срывается шквальным выпадом',
  },
  {
    biomeCode: 'dark-forest',
    code: 'slime-king',
    name: 'Король слизней',
    kind: 'slime',
    isElite: true,
    isBoss: true,
    baseHealth: 70,
    baseAttack: 12,
    baseDefence: 5,
    baseMagicDefence: 3,
    baseDexterity: 8,
    baseIntelligence: 4,
    healthScale: 1.18,
    attackScale: 1.10,
    defenceScale: 1.10,
    magicDefenceScale: 1.08,
    dexterityScale: 1.08,
    intelligenceScale: 1.05,
    baseExperience: 90,
    baseGold: 30,
    runeDropChance: 72,
    lootTable: JSON.stringify({ herb: 2, leather: 2, crystal: 1 }),
    attackText: 'накрывает всей массой',
  },
  {
    biomeCode: 'dark-forest',
    code: 'ash-matron',
    name: 'Пепельная матрона',
    kind: 'mage',
    isElite: true,
    isBoss: true,
    baseHealth: 84,
    baseAttack: 16,
    baseDefence: 4,
    baseMagicDefence: 7,
    baseDexterity: 8,
    baseIntelligence: 12,
    healthScale: 1.17,
    attackScale: 1.11,
    defenceScale: 1.08,
    magicDefenceScale: 1.10,
    dexterityScale: 1.08,
    intelligenceScale: 1.11,
    baseExperience: 96,
    baseGold: 34,
    runeDropChance: 76,
    lootTable: JSON.stringify({ herb: 2, essence: 2, crystal: 1 }),
    attackText: 'заливает поле пепельным пламенем',
  },
  {
    biomeCode: 'dark-forest',
    code: 'granite-warden',
    name: 'Гранитный страж',
    kind: 'knight',
    isElite: true,
    isBoss: true,
    baseHealth: 94,
    baseAttack: 17,
    baseDefence: 8,
    baseMagicDefence: 4,
    baseDexterity: 7,
    baseIntelligence: 5,
    healthScale: 1.18,
    attackScale: 1.11,
    defenceScale: 1.11,
    magicDefenceScale: 1.07,
    dexterityScale: 1.06,
    intelligenceScale: 1.04,
    baseExperience: 102,
    baseGold: 36,
    runeDropChance: 78,
    lootTable: JSON.stringify({ metal: 2, leather: 1, crystal: 1 }),
    attackText: 'обрушивает гранитный молот',
  },
  {
    biomeCode: 'dark-forest',
    code: 'squall-lord',
    name: 'Владыка шквала',
    kind: 'spirit',
    isElite: true,
    isBoss: true,
    baseHealth: 80,
    baseAttack: 16,
    baseDefence: 4,
    baseMagicDefence: 5,
    baseDexterity: 13,
    baseIntelligence: 8,
    healthScale: 1.17,
    attackScale: 1.11,
    defenceScale: 1.07,
    magicDefenceScale: 1.08,
    dexterityScale: 1.12,
    intelligenceScale: 1.07,
    baseExperience: 98,
    baseGold: 34,
    runeDropChance: 76,
    lootTable: JSON.stringify({ essence: 2, herb: 1, crystal: 1 }),
    attackText: 'срывает строй шквальным ударом',
  },
  {
    biomeCode: 'dark-forest',
    code: 'omen-warden',
    name: 'Хранитель предзнамений',
    kind: 'mage',
    isElite: true,
    isBoss: true,
    baseHealth: 78,
    baseAttack: 15,
    baseDefence: 4,
    baseMagicDefence: 8,
    baseDexterity: 9,
    baseIntelligence: 13,
    healthScale: 1.17,
    attackScale: 1.10,
    defenceScale: 1.07,
    magicDefenceScale: 1.10,
    dexterityScale: 1.07,
    intelligenceScale: 1.11,
    baseExperience: 98,
    baseGold: 34,
    runeDropChance: 76,
    lootTable: JSON.stringify({ essence: 2, herb: 1, crystal: 1 }),
    attackText: 'разрывает ход предсказанным ударом',
  },
  {
    biomeCode: 'forgotten-caves',
    code: 'goblin-raider',
    name: 'Гоблин-налётчик',
    kind: 'goblin',
    isElite: false,
    isBoss: false,
    baseHealth: 40,
    baseAttack: 11,
    baseDefence: 4,
    baseMagicDefence: 2,
    baseDexterity: 10,
    baseIntelligence: 4,
    healthScale: 1.16,
    attackScale: 1.10,
    defenceScale: 1.08,
    magicDefenceScale: 1.06,
    dexterityScale: 1.10,
    intelligenceScale: 1.04,
    baseExperience: 34,
    baseGold: 14,
    runeDropChance: 36,
    lootTable: JSON.stringify({ bone: 1, metal: 1 }),
    attackText: 'бьёт ржавым тесаком',
  },
  {
    biomeCode: 'forgotten-caves',
    code: 'cave-troll',
    name: 'Пещерный тролль',
    kind: 'troll',
    isElite: true,
    isBoss: false,
    baseHealth: 92,
    baseAttack: 19,
    baseDefence: 8,
    baseMagicDefence: 3,
    baseDexterity: 5,
    baseIntelligence: 2,
    healthScale: 1.18,
    attackScale: 1.11,
    defenceScale: 1.10,
    magicDefenceScale: 1.05,
    dexterityScale: 1.04,
    intelligenceScale: 1.02,
    baseExperience: 70,
    baseGold: 28,
    runeDropChance: 48,
    lootTable: JSON.stringify({ bone: 2, metal: 2, crystal: 1 }),
    attackText: 'ломает камни и кости одним ударом',
  },
  {
    biomeCode: 'forgotten-caves',
    code: 'goblin-lord',
    name: 'Лорд гоблинов',
    kind: 'goblin',
    isElite: true,
    isBoss: true,
    baseHealth: 140,
    baseAttack: 25,
    baseDefence: 11,
    baseMagicDefence: 7,
    baseDexterity: 14,
    baseIntelligence: 8,
    healthScale: 1.18,
    attackScale: 1.12,
    defenceScale: 1.10,
    magicDefenceScale: 1.08,
    dexterityScale: 1.09,
    intelligenceScale: 1.06,
    baseExperience: 180,
    baseGold: 75,
    runeDropChance: 82,
    lootTable: JSON.stringify({ metal: 3, crystal: 1, essence: 1 }),
    attackText: 'обрушивает град ударов и приказов',
  },
  {
    biomeCode: 'cursed-citadel',
    code: 'dark-knight',
    name: 'Тёмный рыцарь',
    kind: 'knight',
    isElite: false,
    isBoss: false,
    baseHealth: 72,
    baseAttack: 22,
    baseDefence: 10,
    baseMagicDefence: 6,
    baseDexterity: 9,
    baseIntelligence: 8,
    healthScale: 1.17,
    attackScale: 1.11,
    defenceScale: 1.11,
    magicDefenceScale: 1.08,
    dexterityScale: 1.06,
    intelligenceScale: 1.06,
    baseExperience: 66,
    baseGold: 24,
    runeDropChance: 44,
    lootTable: JSON.stringify({ metal: 2, essence: 1 }),
    attackText: 'рубает проклятым клинком',
  },
  {
    biomeCode: 'cursed-citadel',
    code: 'void-mage',
    name: 'Маг пустоты',
    kind: 'mage',
    isElite: true,
    isBoss: false,
    baseHealth: 65,
    baseAttack: 16,
    baseDefence: 5,
    baseMagicDefence: 14,
    baseDexterity: 10,
    baseIntelligence: 22,
    healthScale: 1.15,
    attackScale: 1.07,
    defenceScale: 1.08,
    magicDefenceScale: 1.11,
    dexterityScale: 1.07,
    intelligenceScale: 1.12,
    baseExperience: 94,
    baseGold: 38,
    runeDropChance: 58,
    lootTable: JSON.stringify({ essence: 2, crystal: 2 }),
    attackText: 'выпускает разлом пустоты',
  },
  {
    biomeCode: 'cursed-citadel',
    code: 'lich-king',
    name: 'Король-лич',
    kind: 'lich',
    isElite: true,
    isBoss: true,
    baseHealth: 230,
    baseAttack: 33,
    baseDefence: 16,
    baseMagicDefence: 22,
    baseDexterity: 14,
    baseIntelligence: 28,
    healthScale: 1.18,
    attackScale: 1.11,
    defenceScale: 1.11,
    magicDefenceScale: 1.11,
    dexterityScale: 1.08,
    intelligenceScale: 1.12,
    baseExperience: 420,
    baseGold: 180,
    runeDropChance: 92,
    lootTable: JSON.stringify({ metal: 2, essence: 3, crystal: 3 }),
    attackText: 'обрушивает морозную печать смерти',
  },
  {
    biomeCode: 'abyss',
    code: 'abyss-guard',
    name: 'Страж бездны',
    kind: 'demon',
    isElite: false,
    isBoss: false,
    baseHealth: 130,
    baseAttack: 30,
    baseDefence: 14,
    baseMagicDefence: 10,
    baseDexterity: 14,
    baseIntelligence: 12,
    healthScale: 1.18,
    attackScale: 1.12,
    defenceScale: 1.10,
    magicDefenceScale: 1.08,
    dexterityScale: 1.08,
    intelligenceScale: 1.08,
    baseExperience: 120,
    baseGold: 60,
    runeDropChance: 60,
    lootTable: JSON.stringify({ essence: 2, metal: 2, crystal: 1 }),
    attackText: 'пронзает клинком из тьмы',
  },
  {
    biomeCode: 'abyss',
    code: 'fire-dragon',
    name: 'Огненный дракон',
    kind: 'dragon',
    isElite: true,
    isBoss: false,
    baseHealth: 220,
    baseAttack: 38,
    baseDefence: 18,
    baseMagicDefence: 16,
    baseDexterity: 12,
    baseIntelligence: 18,
    healthScale: 1.19,
    attackScale: 1.12,
    defenceScale: 1.11,
    magicDefenceScale: 1.10,
    dexterityScale: 1.07,
    intelligenceScale: 1.09,
    baseExperience: 210,
    baseGold: 95,
    runeDropChance: 74,
    lootTable: JSON.stringify({ crystal: 2, essence: 2, metal: 2 }),
    attackText: 'выдыхает огненный поток',
  },
  {
    biomeCode: 'abyss',
    code: 'abyss-emperor',
    name: 'Император бездны',
    kind: 'demon',
    isElite: true,
    isBoss: true,
    baseHealth: 380,
    baseAttack: 52,
    baseDefence: 26,
    baseMagicDefence: 24,
    baseDexterity: 18,
    baseIntelligence: 30,
    healthScale: 1.20,
    attackScale: 1.13,
    defenceScale: 1.12,
    magicDefenceScale: 1.11,
    dexterityScale: 1.08,
    intelligenceScale: 1.11,
    baseExperience: 620,
    baseGold: 260,
    runeDropChance: 98,
    lootTable: JSON.stringify({ crystal: 4, essence: 4, metal: 3 }),
    attackText: 'разрывает реальность копьём тьмы',
  },
] satisfies readonly MobTemplateSeedDefinition[];
